In [20]:
import pandas as pd
import numpy as np

In [21]:
# import pandas as pd — create a DataFrame from your products/prices data
# pd.DataFrame({'product': products, 'price': prices_arr, 'qty': qty, 'revenue': revenue})

# Original product and price data
products = [
    "Khaadi Lawn", "J. Kurta", "Peshawari Chappal", "Dalda Oil (5L)", 
    "National Biryani Masala", "Johar Joshanda (Box)", "Dawlance Fridge", 
    "Audionic Earbuds", "Sunsilk Shampoo", "Tapal Danedar"
]
prices = [3600, 4500, 2800, 2600, 130, 600, 85000, 32000, 580, 250]


# "We cannot perform direct mathematical operations (like multiplication and addition) 
# on an entire Python list all at once, whereas NumPy arrays make this process much easier and faster."
prices_arr = np.array(prices)

# Mock quantities for each product
qty = [12, 8, 15, 20, 50, 30, 3, 7, 25, 40]


# Calculate revenue (price * quantity)
revenue = prices_arr * qty

# Create Data Frame
df = pd.DataFrame({
    'product': products,
    'price': prices_arr,
    'qty': qty,
    'revenue': revenue
})

# Save the DataFrame to a CSV file
df.to_csv('products_data.csv')


# Is sary kaam sy hum ny apni 2 lists sy csv files bnai hain

In [22]:
df = pd.read_csv("SuperMarket Analysis.csv")

In [26]:
df.head()    # first 5 rows print
df.info()    # info shows data types and all info
df.describe()  # it shows statistics


# Write 3 Observations about  what you observe about data


#  Observation 1 (Data Quality): The dataset contains 1,000 rows with zero missing values,
# providing a clean and complete mix of numerical and categorical transaction data.


 # Observation 2 (Customer Satisfaction): The average customer Rating is 6.97 out of 10, with scores ranging
 #  strictly between 4.0 and 10.0, indicating overall positive feedback with no extreme negative ratings.


# Observation 3 (Purchase Behavior): The Quantity of items bought per transaction ranges from 1 to 10,
# with a mean of 5.5, showing that the average customer prefers buying medium-sized quantities.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Invoice ID               1000 non-null   object
 1   Branch                   1000 non-null   object
 2   City                     1000 non-null   object
 3   Customer type            1000 non-null   object
 4   Gender                   1000 non-null   object
 5   Product line             1000 non-null   object
 6   Unit price               1000 non-null   float64
 7   Quantity                 1000 non-null   int64
 8   Tax 5%                   1000 non-null   float64
 9   Sales                    1000 non-null   float64
 10  Date                     1000 non-null   object
 11  Time                     1000 non-null   object
 12  Payment                  1000 non-null   object
 13  cogs                     1000 non-null   float64
 14  gross margin percentage  1000 non-null   float64
 15  gross income             1000 non-null   float64
 16  Rating                   1000 non-null   float64
dtypes: float64(7), int64(1), object(9)
memory usage: 132.9+ KB

,Unit price,Quantity,Tax 5%,Sales,cogs,gross margin percentage,gross income,Rating
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.00000,1.000000e+03,1000.000000,1000.00000
mean,55.672130,5.510000,15.379369,322.966749,307.58738,4.761905e+00,15.379369,6.97270
std,26.494628,2.923431,11.708825,245.885335,234.17651,6.131498e-14,11.708825,1.71858
min,10.080000,1.000000,0.508500,10.678500,10.17000,4.761905e+00,0.508500,4.00000
25%,32.875000,3.000000,5.924875,124.422375,118.49750,4.761905e+00,5.924875,5.50000
50%,55.230000,5.000000,12.088000,253.848000,241.76000,4.761905e+00,12.088000,7.00000
75%,77.935000,8.000000,22.445250,471.350250,448.90500,4.761905e+00,22.445250,8.50000
max,99.960000,10.000000,49.650000,1042.650000,993.00000,4.761905e+00,49.650000,10.00000

In [31]:
# Answer 3 questions using pandas: Which city has most sales? What is the average rating? Which product line earns most?
# df['City'].value_counts() is your starting point.

df = pd.read_csv('SuperMarket Analysis.csv')
# first 3 business questions

#City with the most sales (highest total revenue)
# it will sum every individual  country sale and sum ad show more sale above 
city_sales = df.groupby('City')['Sales'].sum().sort_values(ascending=False)
city_sales

City
Naypyitaw    110568.7065
Yangon       106200.3705
Mandalay     106197.6720
Name: Sales, dtype: float64

In [34]:
# What is the average rating
rating = df["Rating"].mean()
rating

np.float64(6.9727)

In [35]:
# Which product line earns most?
product_line = df.groupby('Product line')["Sales"].sum().sort_values(ascending=False)
product_line

Product line
Food and beverages        56144.8440
Sports and travel         55122.8265
Electronic accessories    54337.5315
Fashion accessories       54305.8950
Home and lifestyle        53861.9130
Health and beauty         49193.7390
Name: Sales, dtype: float64

In [36]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [37]:
# Day 1 mini-assignment — submit tonight

# Brief: A small grocery store owner wants to understand his inventory. Using the Supermarket Sales dataset:

# 1. Load the CSV and display the first 10 rows
# 2. Find which product line generates the highest total revenue
# 3. Find which city has the highest average customer rating
# 4. Create a new column profit_estimate = Total × 0.15
# 5. Print: "Total estimated profit: [amount]"

# Deliverable: A Jupyter notebook with clean code + 1 Markdown cell explaining your findings in plain English (as if writing to the store owner).
df = pd.read_csv('SuperMarket Analysis.csv')
prod_line = df.groupby('Product line')["Sales"].sum().sort_values(ascending=False)
prod_line

Product line
Food and beverages        56144.8440
Sports and travel         55122.8265
Electronic accessories    54337.5315
Fashion accessories       54305.8950
Home and lifestyle        53861.9130
Health and beauty         49193.7390
Name: Sales, dtype: float64

In [42]:
# Find which city has the highest average customer rating
city_avg = df.groupby('City')["Rating"].mean().sort_values(ascending=False)
city_avg

City
Naypyitaw    7.072866
Yangon       7.027059
Mandalay     6.818072
Name: Rating, dtype: float64

In [44]:
# Create a new column profit_estimate = Total × 0.15
df['profit_estimate'] = df['Sales'] * 0.15


# Print: "Total estimated profit: [amount]"
total_profit = df['profit_estimate'].sum()
print(f"Total estimated profit: {total_profit: .2f}")

Total estimated profit:  48445.01